import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/organisms/header/Header";
import Footer from "@/components/atoms/footer/Footer";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mainContainer">
          <Header />
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
